Repository LPilogue/LPilogue-FE, pull requests merged in 2025-06, with the labels that each got.

#37 #36 feat: api 인스턴스 작성
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/api/api.js
  src/api/auth/signup.js
  src/pages/Signup.jsx
  vite.config.js
Labels: feat

#39 #38 feat: 유저 api 연결
  src/api/auth/duplicateId.js
  src/api/auth/login.js
  src/pages/Landing.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: feat, API

#49 Feat/#46/docker openweather 환경 변수
  docker-compose.yml
Labels: enhancement

#50 Update docker-image-CD.yml
  .github/workflows/docker-image-CD.yml
Labels: enhancement
